// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dMultinom
Rcpp::NumericVector dMultinom(Rcpp::NumericMatrix probs, Rcpp::NumericVector y, bool lg);
RcppExport SEXP ltools_dMultinom(SEXP probsSEXP, SEXP ySEXP, SEXP lgSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type lg(lgSEXP);
    __result = Rcpp::wrap(dMultinom(probs, y, lg));
    return __result;
END_RCPP
}
