# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Normalize rows to sum to 1
#' 
#' Given a matrix, divide each row by its sum in order to normalize so that
#' each row sums to 1.  Useful for obtaining category probabilities.
#' 
#' Note: doesn't perform any validation or checking
#' 
#' @param M The matrix with rows in need of normalization
#' 
#' @export
#' 
normalize_rows <- function(M) {
    .Call('ltools_normalize_rows', PACKAGE = 'ltools', M)
}

#' Sample from multinomial distribution
#' 
#' Given a matrix of category probabilities, return a matrix of outcomes
#' sampled from multinomial distribution with those category probabilities
#' 
#' Note: doesn't perform any validation or checking
#' 
#' @param probs $N \times K$ matrix of probability of observation $n$ falling 
#' into category $k$
#' @param m How many outcomes should be sampled per row?  Defaults to 1.
#' 
#' @export
#' 
rMultinom <- function(probs, m = 1L) {
    .Call('ltools_rMultinom', PACKAGE = 'ltools', probs, m)
}

