# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluate vector of multinomial densities
#' 
#' @param x Outcome vector, length n
#' @param prob Probability matrix.  Entry ij is P(X_i = j)
#' 
#' @export
dMultinomCpp <- function(x, prob, lg) {
    .Call('ltools_dMultinomCpp', PACKAGE = 'ltools', x, prob, lg)
}

#' Select elements from a matrix based on a vector of column indices
#' 
#' From a matrix and a vector, return a vector where the ith element is the
#' matrix element (i, v[i])
#' 
#' Faster version of M[cbind(1:length(v), v)]
#' 
#' @param M The n by m matrix
#' @param v The length-n vector taking integer values 1 to m
column_picker <- function(M, v) {
    .Call('ltools_column_pickerCpp', PACKAGE = 'ltools', M, v)
}

normalize_rows <- function(M) {
    .Call('ltools_normalize_rowsCpp', PACKAGE = 'ltools', M)
}

getbcl <- function(design_mat, coef_mat) {
    .Call('ltools_getbcl', PACKAGE = 'ltools', design_mat, coef_mat)
}

impute_U_Cpp <- function(Z, Y, M, coef_M, coef_Y, coef_U) {
    .Call('ltools_impute_U_Cpp', PACKAGE = 'ltools', Z, Y, M, coef_M, coef_Y, coef_U)
}

#' Sample from multinomial distribution
#' 
#' Given a matrix of category probabilities, return a matrix of outcomes
#' sampled from multinomial distribution with those category probabilities
#' 
#' Note: doesn't perform any validation or checking
#' 
#' @param probs $N \times K$ matrix of probability of observation $n$ falling 
#' into category $k$
#' @param m How many outcomes should be sampled per row?  Defaults to 1.
#' 
#' @export
#' 
rMultinom <- function(probs, m = 1L) {
    .Call('ltools_rMultinom', PACKAGE = 'ltools', probs, m)
}

